### PR TITLE
fix for satellite and IGD gateway (miniupnpd)

### PR DESCRIPTION
**Pull request by jlabrous**
Here is 2 fixes:
1st is to fix timeout in mwan3track process. Remember satellite has latency around 700 ms 
2nd is to not overwrite mwan3 rules but only clean it:
For satellite, I need to have "Tracking Method" set to IGMP (ping). DNS method gives 1ms !
For ssh and VPN a rule with ordered metric ADSL(1)  SAT(2) and then TUN(3) 
Eventually a weight ordered one with SAT(9) ADSL(1) to replace balanced

### CODE REVIEW

**Comment by simlelievre** [comment]
Hi Jean,
Thanks for your PR.
We're checking and testing it.
Simon

**Comment by jlabrous** [comment]
Next patch can (will ?) be to delete members with "metric" that exceed the number of interface during cleanup.

**Comment by sduponch** [comment]
Hi jean,

"fix timeout for satellite" will be merged in the unstable 0.2.16 release.

if PR "do not delete all rules but only orphans" goal is to keep customs policy, i think we should use another approach in prefixing policies with something, like i already do with the "^dns_".
I think syncing only orphans is less reliable than clean up and redo.

Best regards,
DUPONCHEEL Sébastien

**Comment by jlabrous** [comment]
There is 2 goals in PR "do not delete all rules but only orphans":
- keep customs. Yes you can use another approach using for example ovh_ or
otb_ or auto_ prefix
- not overwriting  "Tracking Method" (and timeout?) because for SAT we
really need a ping
Best regards,
Jean Labrousse

Je suis impatient de tester ça maintenant que je suis en 'testing' :-)


2016-03-16 16:15 GMT+01:00 sduponch <notifications@github.com>:

**Comment by sduponch** [comment]
Linled with https://github.com/ovh/overthebox-feeds/pull/68

**Comment by sduponch** [comment]
Closing PR will be merged in #68

**Pull request closed without merging**
