### PR TITLE
Update glorytun udp start script

### PR DESCRIPTION
**Pull request by gregdel**

### CODE REVIEW

**Comment by sduponch** [comment]
LGTM, maybe you should protect the ${statefile} with double quotes (")

**Comment by angt** [comment]
Don't forget to increment PKG_RELEASE in the Makefile.

**Comment by gregdel** [comment]
I increased the PKG_RELEASE, secured the ${statefile} var and added a lot of comments for @PouuleT

**Comment by angt** [comment]
If you trap `QUIT`, you should raise `QUIT`.
And you should not call `stopped` in the trap, but when `kill -0 ${GTPID}` is `false`.
Also, By removing the call to `stopped` at the end you broke the `TERM` trap.

**Comment by gregdel** [comment]
Why should I raise quit ? I'm trapping EXIT so I can run a function when the script stops.
When ```kill -0 ${GTPID}``` is ```false``` we exit the while loop and the program stops right ? It then calls the ```quit``` function

With this new changes, is the TERM trap still usefull ?

**Comment by angt** [comment]
sorry i read it too fast :)
currently, we trap TERM (sent by procd) and kill all children,
then the main loop stops and we call `stopped`.

**Comment by gregdel** [comment]
If remove the ```kill -TERM ${GTPID}``` line in the stop function, would it be good for you ?

**Comment by angt** [comment]
Yep :) but you still need the `TERM` trap.

**Comment by gregdel** [comment]
Yep I won't remove it :)

**Comment by gregdel** [comment]
Updated

**Pull request merged**
