### PR TITLE
shadowsocks: Fix the detection of the CPU count

### LINKED ISSUE #649: shadowsocks: invalid number of cpu detected in the raspberry pi 3
This command works:
```
 echo $((`cat /sys/devices/system/cpu/present | sed 's/0-//'` + 1))
```

### PR DESCRIPTION
**Pull request by gregdel**
Fixes #649

### CODE REVIEW

**Comment by sduponch** [comment]
/proc/cpu/present does not take care of virtual threaded processors
`
root@compile:~# echo $(cat /sys/devices/system/cpu/present)
0-7
root@compile:~# echo $(awk '{ if ($0~/^physical id/) { p=$NF }; if ($0~/^core id/) { cores[p$NF]=p$NF } } END { for (key in cores) { n++ } } END { print n }' /proc/cpuinfo)
4
`
Rasp processor does not provide core id in /proc/cpuinfo, i suggest to use /sys/devices/system/cpu/present as fallback method if the awk fail.

**Comment by gregdel** [comment]
Is taking the number of virtual cores really an issue ?

**Comment by sduponch** [comment]
Yes because hyperthreading just save cpu registers before switching to another proccess but they does not provide more computing power (or aes modules).

**Comment by gregdel** [comment]
Is doesn't provide more computing power but is really an issue ?

**Comment by sduponch** [comment]
Yes, you will unnecessary overload your system because of an hardware bottleneck: If you are not interested with my opinion do not ask for it. Anyway taking care of virtual processors does not cost much.

**Comment by gregdel** [comment]
I'm trying to figure out the best solution, that's all

**Comment by sduponch** [comment]
root@compile:~# echo $(awk '{ if ($0~/^physical id/) { p=$NF }; if ($0~/^core id/) { cores[p$NF]=p$NF }; if ($0~/processor/) { cpu++ } } END { for (key in cores) { n++ } } END { if (n) {print n} else {print cpu} }' pi3.cpuinfo)
4
root@compile:~# echo $(awk '{ if ($0~/^physical id/) { p=$NF }; if ($0~/^core id/) { cores[p$NF]=p$NF }; if ($0~/processor/) { cpu++ } } END { for (key in cores) { n++ } } END { if (n) {print n} else {print cpu} }' /proc/cpuinfo)
4

**Comment by gregdel** [comment]
Updated

**Pull request merged**
