### PR TITLE
dnsmasq: remove usage of hotplug script and add iptables filters for hosts

### PR DESCRIPTION
**Pull request by sduponch**

### CODE REVIEW

**Comment by gregdel** [comment]
Can you please use shellcheck on your code

**Comment by gregdel** [comment]
Do you even read my comments ?

**Comment by sduponch** [comment]
What don't you understand with WIP tag ?

**Comment by gregdel** [comment]
If you use shellcheck while coding, it will save you a lot of time, you won't have to go over your code again once you think you're done.
It will also make us happy and more confident about this PR :)

**Comment by sduponch** [comment]
Maybe, but i don't know what you're talking about... What is shellcheck ?

**Pull request closed without merging**
