### PR TITLE
overthebox: Remove useless mwan3.socks.dest_ip

### PR DESCRIPTION
**Pull request by angt**
Signed-off-by: Adrien Gallouët <adrien.gallouet@corp.ovh.com>

### CODE REVIEW

**Comment by gregdel** [comment]
It may still be used in the shadowsocks init file, we have to remove it carefully :)

**Comment by angt** [comment]
Used only in `_populate_ipt_socks_bypass_for_mwan_one()` which is no longer called.

**Comment by angt** [comment]
And deleted in #590 :D

**Comment by gregdel** [comment]
Yep but we still need to handle the case where the public IP is directly bound on a wan interface (bridge mode)

**Pull request merged**
